package org.kungfu.generator.easyui;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

import org.kungfu.core.Constants;
import org.kungfu.generator.TableMeta;

import com.jfinal.kit.StrKit;

/**
 * Controller 生成器
 */
public class ControllerGenerator {
	
	protected String packageTemplate =
			"package %s.%s;%n%n";
	protected String importTemplate =
			"import com.jfinal.plugin.activerecord.Page;%n%n" +
			"import org.kungfu.core.Controller;%n%n" +
			"import org.kungfu.core.Constants;%n" +
			"import org.kungfu.util.MsgKit;%n" +
			//"import com.ai.ctos.bdi.config.Const;%n" + //tmp
			//"import com.ai.ctos.bdi.util.MsgKit;%n" + //tmp
			//"import com.ai.ctos.bdi.module.base.BaseController;%n" + //tmp
			"import %s.%s.%s;%n%n";
	protected String classDefineTemplate =
		"/**%n" +
		" * %sController, Generated by Robot on " + Constants.DATE_TIME + ".%n" +
		" */%n" +
		"public class %sController extends BaseController {%n%n" +
		"\tprivate %sService %sService = new %sService();%n%n";
	
	protected String indexTemplate =
			"%n\tpublic void index() {%n%n" +
			"\t}%n%n";
	
	protected String pageTemplate =
			"%n\tpublic void page() {%n" +
			"\t\tPage<%s> page = %sService.page(getParaToInt(\"page\", 1), getParaToInt(\"rows\", 10));%n" +
			"\t\trenderJson(getEasyUIPageJson(page));%n" +
			"\t}%n%n";
	
	protected String dateTimeTemplate = "\t\t\tmodel.set%d(new Date());%n";
	
	protected String saveOrUpdateTemplate =
			"\tpublic void saveOrUpdate() {%n" +
			"\t\t%s model = getBean(%s.class, \"\");%n%n" +
			"\t\tString successMessage = MsgKit.message(model.getId(), Const.SUCCESS_MASSAGE);%n" +
			"\t\tString errorMessage = MsgKit.message(model.getId(), Const.ERROR_MASSAGE);%n%n" +
			"\t\tif (%sService.saveOrUpdate(model))%n" +
			"\t\t\tsuccess(successMessage);%n" +
			"\t\telse%n" +
			"\t\t\terror(errorMessage);%n" +
			"\t}%n%n";
	
	protected String deleteTemplate =
			"\tpublic void delete() {%n%n" +
			"\t\tif (%sService.deleteById(getParaToInt(\"id\", 0)))%n" +
			"\t\tsuccess(Const.SUCCESS_DELETE);%n" +
			"\t\telse%n" +
			"\t\t\terror(Const.ERROR_DELETE);%n" +
			"\t}%n%n";

	
	protected String modelPackageName;
	protected String baseModelPackageName;
	protected String modelOutputDir;
	protected boolean generateDaoInModel = true;
	
	public ControllerGenerator(String modelPackageName, String baseModelPackageName, String modelOutputDir) {
		if (StrKit.isBlank(modelPackageName))
			throw new IllegalArgumentException("modelPackageName can not be blank.");
		if (modelPackageName.contains("/") || modelPackageName.contains("\\"))
			throw new IllegalArgumentException("modelPackageName error : " + modelPackageName);
		if (StrKit.isBlank(baseModelPackageName))
			throw new IllegalArgumentException("baseModelPackageName can not be blank.");
		if (baseModelPackageName.contains("/") || baseModelPackageName.contains("\\"))
			throw new IllegalArgumentException("baseModelPackageName error : " + baseModelPackageName);
		if (StrKit.isBlank(modelOutputDir))
			throw new IllegalArgumentException("modelOutputDir can not be blank.");
		
		this.modelPackageName = modelPackageName;
		this.baseModelPackageName = baseModelPackageName;
		this.modelOutputDir = modelOutputDir;
	}
	
	public void setGenerateDaoInModel(boolean generateDaoInModel) {
		this.generateDaoInModel = generateDaoInModel;
	}
	
	public void generate(List<TableMeta> tableMetas) {
		System.out.println("Generate Controller ...");
		for (TableMeta tableMeta : tableMetas)
			genModelContent(tableMeta);
		wirtToFile(tableMetas);
	}
	
	protected void genModelContent(TableMeta tableMeta) {
		StringBuilder ret = new StringBuilder();
		genPackage(tableMeta, ret);
		genImport(tableMeta, ret);
		genClassDefine(tableMeta, ret);
		genIndexMethod(ret);
		genPageMethod(tableMeta, ret);
		genSaveOrUpdateMethod(tableMeta, ret);
		genDeleteMethod(tableMeta, ret);
		ret.append(String.format("}%n"));
		tableMeta.modelContent = ret.toString();
	}
	
	protected void genPackage(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(packageTemplate, modelPackageName, tableMeta.modelName.toLowerCase().replaceAll("_", "")));
	}
	
	protected void genImport(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(importTemplate, /*modelPackageName.subSequence(0, modelPackageName.lastIndexOf('.')), */modelPackageName, tableMeta.modelName.toLowerCase().replaceAll("_", ""), tableMeta.modelName));
	}
	
	protected void genClassDefine(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(classDefineTemplate, tableMeta.modelName,tableMeta.modelName, tableMeta.modelName, StrKit.firstCharToLowerCase(tableMeta.modelName), tableMeta.modelName));
	}
	
	protected void genIndexMethod(StringBuilder ret) {
		ret.append(String.format(indexTemplate));
	}
	
	protected void genPageMethod(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(pageTemplate, tableMeta.modelName, StrKit.firstCharToLowerCase(tableMeta.modelName)));
	}

	protected void genSaveOrUpdateMethod(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(saveOrUpdateTemplate, tableMeta.modelName, tableMeta.modelName, StrKit.firstCharToLowerCase(tableMeta.modelName)));
	}
	
	protected void genDeleteMethod(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(deleteTemplate, StrKit.firstCharToLowerCase(tableMeta.modelName)));
	}
	
	protected void wirtToFile(List<TableMeta> tableMetas) {
		try {
			for (TableMeta tableMeta : tableMetas)
				wirtToFile(tableMeta);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
	}
	
	/**
	 * 若 model 文件存在，则不生成，以免覆盖用户手写的代码
	 */
	protected void wirtToFile(TableMeta tableMeta) throws IOException {
		File dir = new File(modelOutputDir + File.separator + tableMeta.modelName.toLowerCase().replaceAll("_", "") );
		if (!dir.exists())
			dir.mkdirs();
		
		String target = modelOutputDir + File.separator + tableMeta.modelName.toLowerCase().replaceAll("_", "") + File.separator + tableMeta.modelName + "Controller.java";
		
		File file = new File(target);
		if (file.exists()) {
			return ;	// 若 Model 存在，不覆盖
		}
		
		FileWriter fw = new FileWriter(file);
		try {
			fw.write(tableMeta.modelContent);
		}
		finally {
			fw.close();
		}
	}
}


